### PR TITLE
Add controller offset adjustments

### PR DESCRIPTION
**Pull request by incertia**
Applies the normal SaberTailor adjustments and then moves everything according to the controller offset, in case your controllers are not being reported in the correct location in your default standing location.

Currently the patch set is for version 2.9.0. I'll update this later to target 3.0.3 if there are any additional changes that need to be made.

Menus could use some adjustments, I let it scroll because I was lazy.

There is no need to change the config version, the config loader will automatically detect that there is no offset and apply a default of 0.

### CODE REVIEW

**Comment by incertia** [comment]
Updated for 3.0.3

**Comment by incertia** [comment]
@Shadnix-was-taken bump

**Comment by Shadnix-was-taken** [comment]
Hi. Sorry for not responding anytime sooner - I got drowned in work at my job and probably won't have much time to look over this for another couple of days. That hopefully settles down a bit after Christmas.

There is also the issue that this can (based on the description at least) be used to extend the offsets over the current limit, which is potentially a whole can of worms I'm not sure I want to touch... I have to think about this a bit more.

Again, sorry this took so long for a reply and still will take a bit of time.

**Comment by incertia** [comment]
if limits are a thing for scoresaber submission i can write some code to do something about it, but then again people can just compile their own version without the limits

**Comment by incertia** [comment]
i spoke with uninstaller late january and he was [fine with the idea](https://discord.com/channels/501624026532151296/725851848669659236/805531785354149919) so i basically just kept the limits the same as what is used for normal offset

**Comment by Shadnix-was-taken** [comment]
Again, sorry for the late reply. I'm (again) buried in work at the moment. 

Thanks for pointing to that conversation. Sounds like this should be good to go then. I'll try to review the PR in the next couple of days.

**Pull request merged**
